# Generated by Django 4.2.3 on 2023-08-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data_oder',
            new_name='data_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Oder',
            new_name='Order',
        ),
    ]
